### ISSUE TITLE
Ankles don't break when travelling between an oasis/camp and another oasis/camp.

### ISSUE THREAD

**Issue by quartata** [newbiedoodle/DesertSurvival#6]
The ankle break check is only done on sand tiles, which doesn't make much sense IMO.

**Comment by newbiedoodle** [comment]
Have you ever tried walking on sand with a heavy pack? It's hard. Really hard. I you aren't careful, you can slip and break an ankle. I'm assuming camps – even deserted ones – would be built on firmer stuff, and the sand around an oasis is much firmer because it's water-soaked, so you're less likely to get hurt.

**Comment by quartata** [comment]
Fair enough. Ankles probably *should* break on other tiles, but maybe it could be higher weight for that to happen.

**Comment by newbiedoodle** [comment]
Yeah, that's a fair point. I'll drop that into the new version right now as it's half a line of code :P
